In [161]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import spline
import numpy as np
import seaborn as sns
import copy
import numpy as np
#from sklearn
from pomegranate import *
#from acled_vis import *

In [162]:
model = HiddenMarkovModel()

In [246]:
frame = pd.read_csv('jaspreet_afghanistan.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2013)
year2 = (frame.jaspreet_2014)
year3 = (frame.jaspreet_2015)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2017)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year1,year2,year3,year4,year5))
#yeardata.append(year2)
#yeardata.append(year3)
#yeardata.append(year4)
#yeardata.append(year5)
#print(yeardata.T)

yeardata = yeardata.T - 1
print(yeardata[33,:])
#print(yeardata[1:30,:])
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata[1:30,:])
#model.predict(yeardata, algorithm='viterbi')
output = model.fit(yeardata[1:30,:], algorithm='viterbi')
#print(yeardata[7,:])

#print("cool is")
#print(cool)
#print(cool[4,:])
count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 31
for i in range(temp,len(frame.Country)):
    cool = model.predict_proba(yeardata[i,:])
    print(i)
    #print("cool is")
    #print(cool)
    if(np.argmax(cool[4,:],axis =0) == yeardata[i,4]):
        output_diagnol.append(yeardata[i,4])
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        print("else part here")
        print(i)
        key = yeardata[i,4]
        #print("key is")
        #print(key)
        #print("value is")
        #print(np.argmax(cool[4,:],axis =0))
        output[key] = (np.argmax(cool[4,:],axis =0))                       
        
        
print("accuracy for Afghanistan is") 
print(count/(len(frame.Country)-temp))
print(output)
print(output_diagnol)

        
#temp = 21, accuracy for Afghanistan is
#0.46153846153846156
#temp=26, -> 0.5
#temp=31 -> 0.666

34
[2 1 1 1 2]
31
32
else part here
32
key is
2
value is
4
33
accuracy for Afghanistan is
0.6666666666666666
{2: 4}
[1, 2]


In [257]:
frame = pd.read_csv('jaspreet_niger.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year1,year2,year3,year4,year5,year6,year7,year8))
#yeardata.append(year2)
#yeardata.append(year3)
#yeardata.append(year4)
#yeardata.append(year5)
#print(yeardata.T)

yeardata = yeardata.T - 1
#print(yeardata)

yeardata = yeardata[yeardata.min(axis=1)>=0,:]

print("new shape is")
print(yeardata.shape)
#print(yeardata[1:30,:])
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata[1:25,:])
#model.predict(yeardata, algorithm='viterbi')
output = model.fit(yeardata[1:25,:], algorithm='viterbi')
#print(yeardata[7,:])
'''
#print("cool is")
#print(cool)
#print(cool[4,:])
count = 0


temp = 26
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("cool is")
    #print(cool)
    if (np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        count+=1
        
print("accuracy for Niger is") 
print(count/(yeardata.shape[0]-temp))
'''

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 26
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("no of values")
    #print()
    #print(i)
    #print("cool is")
    #print(cool)
    #print("next loop start")
    #print("value 1 is")
    #print(yeardata[i,7])
    
    #print("value 2 is")
    #print(np.argmax(cool[7,:],axis =0))
    if(np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        output_diagnol.append(yeardata[i,7])
        print("value match")
        print(yeardata[i,7])
        print("end")
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        #print("else part here")
        #print(i)
        print("not match start")
        key = yeardata[i,7]
        print("key is")
        print(key)
        print("value is")
        print(np.argmax(cool[7,:],axis =0))
        print("not match end")
        output[key] = (np.argmax(cool[7,:],axis =0))                       
        
        
print("accuracy for Mali is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)
#temp = 41
#accuracy = 5
#temp=46
#accuracy=6.66
#temp=51
#acc = 10

####after removing zeroes
#31 - 5.88
#26- 9.09


61
new shape is
(48, 8)
value match
2
end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
0
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
0
value is
4
not match end
not match start
key is
1
value is
3
not match end
value match
2
end
not match start
key is
2
value is
3
not match end
not match start
key is
0
value is
4
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
0
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
0
value is
3
not match end
not match start
key is
0
value is
3
not match end
not match start
key is
1
value is
3
not match end
not match start
key is
1
value is
3
not 

In [258]:
frame = pd.read_csv('jaspreet_mali.csv')

print(len(frame.Country))
year0 = (frame.jaspreet_2013)
year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year0,year1,year2,year3,year4,year5,year6,year7,year8))
#print("yeardata is")
#print(yeardata)
#yeardata.append(year2)
#yeardata.append(year3)
#yeardata.append(year4)
#yeardata.append(year5)
#print(yeardata.T)

yeardata = yeardata.T - 1
print(yeardata)
#print(yeardata[1:30,:])
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata[1:40,:])
#model.predict(yeardata, algorithm='viterbi')
output = model.fit(yeardata[1:40,:], algorithm='viterbi')
#print(yeardata[7,:])

#print("cool is")
#print(cool)
#print(cool[4,:])
'''
count = 0

temp = 41
for i in range(temp,len(frame.Country)):
    cool = model.predict_proba(yeardata[i,:])
    #print("cool is")
    #print(cool)
    if (np.argmax(cool[8,:],axis =0) == yeardata[i,8]):
        count+=1
        
print("accuracy for Mali is") 
print(count/(len(frame.Country)-temp))
'''

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 41
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("no of values")
    #print()
    #print(i)
    #print("cool is")
    #print(cool)
    #print("next loop start")
    #print("value 1 is")
    #print(yeardata[i,7])
    
    #print("value 2 is")
    #print(np.argmax(cool[7,:],axis =0))
    if(np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        output_diagnol.append(yeardata[i,7])
        print("value match")
        print(yeardata[i,7])
        print("end")
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        #print("else part here")
        #print(i)
        print("not match start")
        key = yeardata[i,7]
        print("key is")
        print(key)
        print("value is")
        print(np.argmax(cool[7,:],axis =0))
        print("not match end")
        output[key] = (np.argmax(cool[7,:],axis =0))                       
        
        
print("accuracy for Mali is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)


#temp = 36; 7.692
#temp = 41; 37.5


49
[[1 2 1 0 0 0 1 0 0]
 [2 2 2 0 0 1 1 0 1]
 [1 2 1 0 0 1 1 0 0]
 [2 2 1 0 1 1 2 1 2]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [2 2 1 1 1 0 0 0 0]
 [2 2 0 1 1 0 0 0 1]
 [2 1 0 0 1 0 0 1 1]
 [2 2 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 2]
 [1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 2 1 0 0 0 0 0 0]
 [1 2 1 1 0 0 0 1 1]
 [2 2 2 1 0 0 1 1 1]
 [2 2 1 1 

In [263]:
frame = pd.read_csv('jaspreet_somalia.csv')

print(len(frame.Country))
#year0 = (frame.jaspreet_2010)
#year1 = (frame.jaspreet_2011)
#year2 = (frame.jaspreet_2011_2)
year3 = (frame.jaspreet_2012)
year4 = (frame.jaspreet_2012_2)
year5 = (frame.jaspreet_2013)
year6 = (frame.jaspreet_2013_2)
year7 = (frame.jaspreet_2014)
year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year3,year4,year5,year6,year7,year8,year9,year10,year11,year12,year13,year14,year15))
#yeardata.append(year2)
#yeardata.append(year3)
#yeardata.append(year4)
#yeardata.append(year5)
#print(yeardata.T)
#print(yeardata.shape)
#print("yeardata is")
#print(yeardata[:,71])
yeardata = yeardata.T - 1
#print(yeardata[71,:])

#print(yeardata[1,14])
#print(yeardata[1:30,:])
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata[1:65,:])
#model.predict(yeardata, algorithm='viterbi')
output = model.fit(yeardata[1:65,:], algorithm='viterbi')

'''
count = 0

temp = 66
for i in range(temp,len(frame.Country)):
    cool = model.predict_proba(yeardata[i,:])
    #print("cool is")
    #print(cool)
    if (np.argmax(cool[12,:],axis =0) == yeardata[i,12]):
        count+=1
        
print("accuracy for somalia is") 
print(count/(len(frame.Country)-temp))
'''
count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 66
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("no of values")
    #print()
    #print(i)
    #print("cool is")
    #print(cool)
    #print("next loop start")
    #print("value 1 is")
    #print(yeardata[i,7])
    
    #print("value 2 is")
    #print(np.argmax(cool[7,:],axis =0))
    if(np.argmax(cool[12,:],axis =0) == yeardata[i,12]):
        output_diagnol.append(yeardata[i,12])
        print("value match")
        print(yeardata[i,12])
        print("end")
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        #print("else part here")
        #print(i)
        print("not match start")
        key = yeardata[i,12]
        print("key is")
        print(key)
        print("value is")
        print(np.argmax(cool[12,:],axis =0))
        print("not match end")
        output[key] = (np.argmax(cool[12,:],axis =0))                       
        
        
print("accuracy for Somalia is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)

#temp = 56 ; 11.764
#temp = 61; 33.3
#temp=66; 57.142
#temp=71; 0.5


73
value match
1
end
value match
1
end
not match start
key is
2
value is
3
not match end
value match
1
end
not match start
key is
1
value is
0
not match end
value match
1
end
not match start
key is
1
value is
0
not match end
accuracy for Somalia is
0.5714285714285714
{2: 3, 1: 0}
[1, 1, 1, 1]


In [265]:
frame = pd.read_csv('jaspreet_southsudan.csv')

print(len(frame.country))
#year0 = (frame.jaspreet_2010)
#year1 = (frame.jaspreet_2011)
#year2 = (frame.jaspreet_2011_2)
#year3 = (frame.jaspreet_2012)
#year4 = (frame.jaspreet_2012_2)
#year5 = (frame.jaspreet_2013)
#year6 = (frame.jaspreet_2013_2)
year7 = (frame.jaspreet_2014)
#year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year7,year9,year10,year11,year12,year13,year14,year15))
#yeardata.append(year2)
#yeardata.append(year3)
#yeardata.append(year4)
#yeardata.append(year5)
#print(yeardata.T)
#print(yeardata.shape)
#print("yeardata is")
#print(yeardata[:,71])
yeardata = yeardata.T - 1



yeardata = yeardata[yeardata.min(axis=1)>=0,:]

print("new shape is")
print(yeardata.shape)
 
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata[1:60,:])
#model.predict(yeardata, algorithm='viterbi')
output = model.fit(yeardata[1:60,:], algorithm='viterbi')
#print(yeardata[71,:])

#print("cool is")
#print(cool)
#print(cool[4,:])
'''
count = 0

temp = 61
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("cool is")
    #print(cool)
    if (np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        count+=1
        
print("accuracy for southsudan is") 
print(count/(yeardata.shape[0]-temp))
'''

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 61
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("no of values")
    #print()
    #print(i)
    #print("cool is")
    #print(cool)
    #print("next loop start")
    #print("value 1 is")
    #print(yeardata[i,7])
    
    #print("value 2 is")
    #print(np.argmax(cool[7,:],axis =0))
    if(np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        output_diagnol.append(yeardata[i,7])
        print("value match")
        print(yeardata[i,7])
        print("end")
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        #print("else part here")
        #print(i)
        print("not match start")
        key = yeardata[i,7]
        print("key is")
        print(key)
        print("value is")
        print(np.argmax(cool[7,:],axis =0))
        print("not match end")
        output[key] = (np.argmax(cool[7,:],axis =0))                       
        
        
print("accuracy for South Sudan is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)
#for 56, 11.11%
#for 61, 15.38%
#for 66, 12%
#for 71



78
new shape is
(74, 8)
not match start
key is
2
value is
1
not match end
not match start
key is
2
value is
1
not match end
value match
1
end
not match start
key is
2
value is
3
not match end
not match start
key is
2
value is
1
not match end
not match start
key is
2
value is
3
not match end
value match
3
end
not match start
key is
2
value is
3
not match end
not match start
key is
2
value is
1
not match end
not match start
key is
2
value is
1
not match end
not match start
key is
2
value is
1
not match end
not match start
key is
2
value is
1
not match end
not match start
key is
2
value is
3
not match end
accuracy for South Sudan is
0.15384615384615385
{2: 3}
[1, 3]
