In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import spline
import numpy as np
import seaborn as sns
import copy
import numpy as np
#from sklearn
from pomegranate import *
#from acled_vis import *

In [2]:
model = HiddenMarkovModel()

In [3]:
frame = pd.read_csv('jaspreet_afghanistan.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2013)
year2 = (frame.jaspreet_2014)
year3 = (frame.jaspreet_2015)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2017)



yeardata = np.empty([1,1])


yeardata = np.vstack((year1,year2,year3,year4,year5))


yeardata = yeardata.T - 1
#print(yeardata)
yeardata = yeardata[yeardata.min(axis=1)>=0,:]

print("new shape is")
print(yeardata.shape)
yeardata = yeardata.tolist()
print(yeardata)
print("final shape is")
print(len(yeardata))
#newyear = yeardata
#yeardata = yeardata[:,0:3]
#print(yeardata)

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata ,algorithm='baum-welch')
#model.predict(yeardata, algorithm='viterbi')
#model = model.fit(yeardata[1:33,0:3], algorithm='viterbi')

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 1
for i in range(temp,len(yeardata)):
    print("yeardata is")
    print(yeardata[i])
    cool = model.predict_proba(yeardata[i,:])
    #print("cool is")
    #print(cool)
    cool1 = model.predict(yeardata[i,:], algorithm='map')
    cool2 = model.viterbi(yeardata[i,:])
    print("cool2 is")
    print(cool2)
    #print("shape of cool is")
    #print(cool.shape)
    if(cool1[1] == yeardata[i,4]):
        output_diagnol.append(yeardata[i,4])
        print("Theres a match!")
        #print("yeardata is")
        #print(yeardata[i,4])
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        #print("else part here")
        #print(i)
        key = yeardata[i,4]
        #print("key is")
        #print(key)
        #print("value is")
        #print(np.argmax(cool[4,:],axis =0))
        output[key] = (cool1[1])                       
        
print("correct count is")
print(count)
print("accuracy for Afghanistan is") 
print(count/(len(frame.Country)-temp))
print(output)
print(output_diagnol)

        
#temp = 21, accuracy for Afghanistan is
#0.46153846153846156
#temp=26, -> 0.5
#temp=31 -> 0.666

#5 -> 9.09
#2 -> 36.36
#3 -> 42.42

34
new shape is
(32, 5)
[[3, 3, 2, 2, 2], [2, 2, 1, 2, 3], [1, 1, 1, 2, 1], [2, 2, 1, 1, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 2], [3, 2, 2, 2, 2], [0, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 2, 1, 1, 1], [0, 0, 1, 1, 1], [1, 1, 1, 2, 2], [2, 1, 1, 2, 2], [0, 1, 1, 1, 2], [1, 1, 1, 2, 2], [1, 1, 1, 2, 1], [2, 1, 1, 1, 1], [1, 1, 1, 2, 2], [2, 2, 2, 2, 2], [2, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [2, 2, 1, 1, 2], [1, 2, 1, 2, 1], [1, 2, 1, 1, 2], [1, 1, 1, 2, 2], [1, 2, 0, 1, 1], [2, 2, 1, 2, 2], [2, 1, 1, 1, 2]]
final shape is
32
yeardata is
[2, 2, 1, 2, 3]


TypeError: list indices must be integers or slices, not tuple

In [69]:
frame = pd.read_csv('jaspreet_niger.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])


yeardata = np.vstack((year1,year2,year3,year4,year5,year6,year7,year8))


yeardata = yeardata.T - 1
#print(yeardata)

yeardata = yeardata[yeardata.min(axis=1)>=0,:]

print("new shape is")
print(yeardata.shape)
#print(yeardata[1:30,:])
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=2, X=yeardata[1:47,0:6])
#model.predict(yeardata, algorithm='viterbi')
#output1 = model.fit(yeardata[1:47,0:6], algorithm='baum-welch')
#print(yeardata[7,:])
count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 1
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("cool shape")
    #print(cool.shape)
    
    if(np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        output_diagnol.append(yeardata[i,7])
        
        count+=1
    else:
        key = yeardata[i,7]
        output[key] = (np.argmax(cool[7,:],axis =0))                       
        
        
print("accuracy for Niger is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)
#temp = 41
#accuracy = 5
#temp=46
#accuracy=6.66
#temp=51
#acc = 10

####after removing zeroes
#31 - 5.88
#26- 9.09

#5 compos 

#2 compos = 59.57
#5 = 17.02
#3 -> 40.42


61
new shape is
(48, 8)
accuracy for Niger is
0.5957446808510638
{2: 0, 0: 1, 1: 0}
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [117]:
frame = pd.read_csv('jaspreet_mali.csv')

print(len(frame.Country))
year0 = (frame.jaspreet_2013)
year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year0,year1,year2,year3,year4,year5,year6,year7,year8))


yeardata = yeardata.T - 1
print(yeardata)
#print(yeardata[1:30,:])
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=3, X=yeardata[1:48,0:6], algorithm = 'baum-welch')
#model.predict(yeardata, algorithm='viterbi')
#output1 = model.fit(yeardata[1:48,0:6], algorithm='viterbi')

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 1
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    if(np.argmax(cool[7,:],axis =0) == yeardata[i,7]):
        output_diagnol.append(yeardata[i,7])
        count+=1
    else:
        key = yeardata[i,7]
        output[key] = (np.argmax(cool[7,:],axis =0))                       
        
print("count is")
print(count)
print("accuracy for Mali is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)


#temp = 36; 7.692
#temp = 41; 37.5

#5 compos = 0
#3 compos = 12.5
#2 = 2.083



49
[[1 2 1 0 0 0 1 0 0]
 [2 2 2 0 0 1 1 0 1]
 [1 2 1 0 0 1 1 0 0]
 [2 2 1 0 1 1 2 1 2]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [2 2 1 1 1 0 0 0 0]
 [2 2 0 1 1 0 0 0 1]
 [2 1 0 0 1 0 0 1 1]
 [2 2 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 2]
 [1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 2 1 0 0 0 0 0 0]
 [1 2 1 1 0 0 0 1 1]
 [2 2 2 1 0 0 1 1 1]
 [2 2 1 1 

In [113]:
frame = pd.read_csv('jaspreet_somalia.csv')

print(len(frame.Country))
#year0 = (frame.jaspreet_2010)
#year1 = (frame.jaspreet_2011)
#year2 = (frame.jaspreet_2011_2)
year3 = (frame.jaspreet_2012)
year4 = (frame.jaspreet_2012_2)
year5 = (frame.jaspreet_2013)
year6 = (frame.jaspreet_2013_2)
year7 = (frame.jaspreet_2014)
year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])
yeardata = np.vstack((year3,year4,year5,year6,year7,year8,year9,year10,year11,year12,year13,year14,year15))

yeardata = yeardata.T - 1

yeardata = yeardata[yeardata.min(axis=1)>=0,:]

print("new shape is")
print(yeardata.shape)



#print(yeardata)
model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=5, X=yeardata[1:55,0:11], algorithm = 'baum-welch')
#model.predict(yeardata, algorithm='viterbi')
#output = model.fit(yeardata[1:72,:0:11], algorithm='viterbi')

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 1
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    if(np.argmax(cool[12,:],axis =0) == yeardata[i,12]):
        output_diagnol.append(yeardata[i,12])
        count+=1
    else:
        key = yeardata[i,12]
        output[key] = (np.argmax(cool[12,:],axis =0))                       
        
        
print("accuracy for Somalia is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)

#temp = 56 ; 11.764
#temp = 61; 33.3
#temp=66; 57.142
#temp=71; 0.5

# 5 comp = 40
# 3 comp = 12.72
# 2 comp = 0


73
new shape is
(56, 13)
accuracy for Somalia is
0.4
{1: 3, 2: 4, 3: 0}
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [31]:
frame = pd.read_csv('jaspreet_southsudan.csv')

print(len(frame.country))

year7 = (frame.jaspreet_2014)
#year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year7,year9,year10,year11,year12,year13,year14,year15))

yeardata = yeardata.T - 1
yeardata = yeardata[yeardata.min(axis=1)>=0,:]

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=4, X=yeardata[1:77,0:6], algorithm = 'baum-welch')
#model.predict(yeardata, algorithm='viterbi')
#output = model.fit(yeardata[1:77,0:6], algorithm='viterbi')

count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 1
for i in range(temp,yeardata.shape[0]):
    cool = model.predict_proba(yeardata[i,:])
    #print("cool is")
    #print(cool)
    cool1 = model.predict(yeardata[i,:], algorithm='map')
    #print("cool1 shape is")
    #print(cool1.shape)
    if(cool1[7] == yeardata[i,7]):
        output_diagnol.append(yeardata[i,7])
        count+=1
    else:
        key = yeardata[i,7]
        output[key] = (np.argmax(cool[7,:],axis =0))                       
        
print("count is ")
print(count)
print("accuracy for South Sudan is") 
print(count/(yeardata.shape[0]-temp))
print(output)
print(output_diagnol)
#for 56, 11.11%
#for 61, 15.38%
#for 66, 12%
#for 71

#5 components = 23.23
#2 = 15.06
#3 = 13.69



78
count is 
17
accuracy for South Sudan is
0.2328767123287671
{2: 1, 1: 0}
[1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 3, 1, 3, 3, 1, 1, 3]
