In [79]:
import numpy as np
#from sklearn
from pomegranate import *
import pandas as pd
from collections import Counter

In [80]:
model = HiddenMarkovModel()


In [166]:
frame = pd.read_csv('jaspreet_southsudan.csv')

print(len(frame.country))

year7 = (frame.jaspreet_2014)
#year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])


yeardata = np.vstack((year7,year9,year10,year11,year12,year13,year14))

yeardata1 = np.vstack((year7,year9,year10,year11,year12,year13,year14,year15))

ndvi_14 = (frame.ndvi_14)
#ndvi_14_2 = (frame.ndvi_14_2)
ndvi_15 = (frame.ndvi_15)
ndvi_15_2 = (frame.ndvi_15_2)
ndvi_16 = (frame.ndvi_16)
ndvi_16_2 = (frame.ndvi_16_2)
ndvi_17 = (frame.ndvi_17)
ndvi_17_2 = (frame.ndvi_17_2)
ndvi_18 = (frame.ndvi_18)

print("this part complete")



#ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi_14,ndvi_15,ndvi_15_2,ndvi_16,ndvi_16_2,ndvi_17,ndvi_17_2))
ndvidata1 = np.vstack((ndvi_14,ndvi_15,ndvi_15_2,ndvi_16,ndvi_16_2,ndvi_17,ndvi_17_2,ndvi_18))

ndvidata = ndvidata.T 
ndvidata1 = ndvidata1.T 

#yeardata = np.empty([1,1])
#yeardata = np.vstack((year1,year2,year3,year4))
#yeardata1 = np.vstack((year1,year2,year3,year4,year5))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

print(yeardata.shape[0])

print("ndvi shape is")
print(ndvidata.shape)
ndvidata = ndvidata[yeardata1.min(axis=1)>=0,:]
ndvidata1 = ndvidata1[yeardata1.min(axis=1)>=0,:]
yeardata = yeardata[yeardata1.min(axis=1)>=0,:]
print("yeardata shape is")
print(yeardata.shape[0])
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

year = np.array((yeardata))
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
ndvidata = ndvidata.tolist()
ndvidata1 = ndvidata1.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))
year1 = np.array((yeardata1))
ndvi1 = np.array((ndvidata1))

inputs = np.dstack((year,ndvi))
inputs1 = np.dstack((year1,ndvi1))

inputs = np.reshape(inputs,(74,7,2))
inputs1 = np.reshape(inputs1,(74,8,2))

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=2, X=inputs ,algorithm='baum-welch', verbose=False, emission_pseudocount=0.5, end_state=False)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
counter_mat = 0
counter_prob = 0
class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0

for j in range(temps,74):
    matrix =[]
    comparison = inputs1[j][7][0]
    
    for i in range(0,5):
        temph = inputs1[j][:][:]
        #print(temph.shape)
        temph[7][0] = i
        probability = model.log_probability(temph)
        matrix.append(probability)
    ind = matrix.index(max(matrix))
    if comparison == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1

print("accuracy_prob of south sudan is")
print(counter_prob)
print(counter_prob/74)
print("classwise accuracies are")
print("Class 0")
print(class0/74)
print("Class 1")
print(class1/74)
print("Class 2")
print(class2/74)
print("Class 3")
print(class3/74)
print("Class 4")
print(class4/74)

78
this part complete
78
ndvi shape is
(78, 7)
yeardata shape is
74
accuracy_prob of south sudan is
56
0.7567567567567568
classwise accuracies are
Class 0
0.0
Class 1
0.05405405405405406
Class 2
0.7027027027027027
Class 3
0.0
Class 4
0.0


In [154]:
frame = pd.read_csv('jaspreet_somalia.csv')
print(len(frame.Country))

#year0 = (frame.jaspreet_2010)
#year1 = (frame.jaspreet_2011)
#year2 = (frame.jaspreet_2011_2)
year3 = (frame.jaspreet_2012)
year4 = (frame.jaspreet_2012_2)
year5 = (frame.jaspreet_2013)
year6 = (frame.jaspreet_2013_2)
year7 = (frame.jaspreet_2014)
year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)

#ndvi_10 = (frame.ndvi_10)
#ndvi_11 = (frame.ndvi_11)
#ndvi_11_2 = (frame.ndvi_11_2)
ndvi_12 = (frame.ndvi_12)
ndvi_12_2 = (frame.ndvi_12_2)
ndvi_13 = (frame.ndvi_13)
ndvi_13_2 = (frame.ndvi_13_2)
ndvi_14 = (frame.ndvi_14)
ndvi_14_2 = (frame.ndvi_14_2)
ndvi_15 = (frame.ndvi_15)
ndvi_15_2 = (frame.ndvi_15_2)
ndvi_16 = (frame.ndvi_16)
ndvi_16_2 = (frame.ndvi_16_2)
ndvi_17 = (frame.ndvi_17)
ndvi_17_2 = (frame.ndvi_17_2)
ndvi_18 = (frame.ndvi_18)

#yeardata = np.empty([1,1])
yeardata1 = np.vstack((year3,year4,year5,year6,year7,year8,year9,year10,year11,year12,year13,year14,year15))
yeardata = np.vstack((year3,year4,year5,year6,year7,year8,year9,year10,year11,year12,year13,year14))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

#print(yeardata1)

#yeardata = yeardata[yeardata.min(axis=1)>=0,:]
#yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print(yeardata1.shape[0])
print("this part complete")

#ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi_12,ndvi_12_2,ndvi_13,ndvi_13_2,ndvi_14,ndvi_14_2,ndvi_15,ndvi_15_2,ndvi_16,ndvi_16_2,ndvi_17,ndvi_17_2))
ndvidata1 = np.vstack((ndvi_12,ndvi_12_2,ndvi_13,ndvi_13_2,ndvi_14,ndvi_14_2,ndvi_15,ndvi_15_2,ndvi_16,ndvi_16_2,ndvi_17,ndvi_17_2,ndvi_18))

ndvidata = ndvidata.T 
ndvidata1 = ndvidata1.T 
print("ndvi shape is")
print(ndvidata.shape)
ndvidata = ndvidata[yeardata1.min(axis=1)>=0,:]
ndvidata1 = ndvidata1[yeardata1.min(axis=1)>=0,:]
yeardata = yeardata[yeardata1.min(axis=1)>=0,:]
print("yeardata shape is")
print(yeardata.shape[0])
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

year = np.array((yeardata))
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
ndvidata = ndvidata.tolist()
ndvidata1 = ndvidata1.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))
year1 = np.array((yeardata1))
ndvi1 = np.array((ndvidata1))

inputs = np.dstack((year,ndvi))
inputs1 = np.dstack((year1,ndvi1))

inputs = np.reshape(inputs,(56,12,2))
inputs1 = np.reshape(inputs1,(56,13,2))

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=3, X=inputs ,algorithm='viterbi', verbose=False, emission_pseudocount=0.5, end_state=False)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
counter_mat = 0
counter_prob = 0
class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0

for j in range(temps,56):
    matrix =[]
    comparison = inputs1[j][12][0]
    
    for i in range(0,5):
        temph = inputs1[j][:][:]
        #print(temph.shape)
        temph[12][0] = i
        probability = model.log_probability(temph)
        matrix.append(probability)
    ind = matrix.index(max(matrix))
    if comparison == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1

print("accuracy_prob of somalia is")
print(counter_prob)
print(counter_prob/56)
print("classwise accuracies are")
print("Class 0")
print(class0/56)
print("Class 1")
print(class1/56)
print("Class 2")
print(class2/56)
print("Class 3")
print(class3/56)
print("Class 4")
print(class4/56)

73
73
this part complete
ndvi shape is
(73, 12)
yeardata shape is
56
accuracy_prob of somalia is
38
0.6785714285714286
classwise accuracies are
Class 0
0.0
Class 1
0.6785714285714286
Class 2
0.0
Class 3
0.0
Class 4
0.0


In [167]:
frame = pd.read_csv('jaspreet_niger.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2) 
#year8 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])


yeardata = np.vstack((year1,year2,year3,year4,year5,year6))

yeardata1 = np.vstack((year1,year2,year3,year4,year5,year6,year7))

print("this part complete")

#ndvi2012 = (frame.ndvi2012)
#ndvi2013 = (frame.ndvi2013)
ndvi2014 = (frame.ndvi2014)
ndvi2015_1 = (frame.ndvi2015_1)
ndvi2015 = (frame.ndvi2015)
ndvi2016_1 = (frame.ndvi2016_1)
ndvi2016 = (frame.ndvi2016)
ndvi2017_1 = (frame.ndvi2017_1)
ndvi2017 = (frame.ndvi2017)


#ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi2014,ndvi2015_1,ndvi2015,ndvi2016_1,ndvi2016,ndvi2017_1))
ndvidata1 = np.vstack((ndvi2014,ndvi2015_1,ndvi2015,ndvi2016_1,ndvi2016,ndvi2017_1,ndvi2017))

#yeardata = np.empty([1,1])
#yeardata = np.vstack((year1,year2,year3,year4))
#yeardata1 = np.vstack((year1,year2,year3,year4,year5))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

print(yeardata.shape[0])
ndvidata = ndvidata.T 
ndvidata1 = ndvidata1.T 
print("ndvi shape is")
print(ndvidata.shape)
ndvidata = ndvidata[yeardata1.min(axis=1)>=0,:]
ndvidata1 = ndvidata1[yeardata1.min(axis=1)>=0,:]
yeardata = yeardata[yeardata1.min(axis=1)>=0,:]
print("yeardata shape is")
print(yeardata.shape[0])
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

year = np.array((yeardata))
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
ndvidata = ndvidata.tolist()
ndvidata1 = ndvidata1.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))
year1 = np.array((yeardata1))
ndvi1 = np.array((ndvidata1))

inputs = np.dstack((year,ndvi))
inputs1 = np.dstack((year1,ndvi1))

inputs = np.reshape(inputs,(48,6,2))
inputs1 = np.reshape(inputs1,(48,7,2))

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=6, X=inputs ,algorithm='viterbi', verbose=False, emission_pseudocount=0.5, end_state=False)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
counter_mat = 0
counter_prob = 0
class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0

for j in range(temps,48):
    matrix =[]
    comparison = inputs1[j][6][0]
    
    for i in range(0,5):
        temph = inputs1[j][:][:]
        #print(temph.shape)
        temph[6][0] = i
        probability = model.log_probability(temph)
        matrix.append(probability)
    ind = matrix.index(max(matrix))
    if comparison == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1

print("accuracy_prob of niger is")
print(counter_prob)
print(counter_prob/48)
print("classwise accuracies are")
print("Class 0")
print(class0/48)
print("Class 1")
print(class1/48)
print("Class 2")
print(class2/48)
print("Class 3")
print(class3/48)
print("Class 4")
print(class4/48)

61
this part complete
61
ndvi shape is
(61, 6)
yeardata shape is
48
accuracy_prob of niger is
38
0.7916666666666666
classwise accuracies are
Class 0
0.7083333333333334
Class 1
0.0625
Class 2
0.020833333333333332
Class 3
0.0
Class 4
0.0


In [91]:
frame = pd.read_csv('jaspreet_afghanistan.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2013)
year2 = (frame.jaspreet_2014)
year3 = (frame.jaspreet_2015)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2017)

ndvi2012 = (frame.AVG_2012)
ndvi2013 = (frame.AVG_2013)
ndvi2014 = (frame.AVG_2014)
ndvi2015 = (frame.AVG_2015)
ndvi2016 = (frame.AVG_2016)
ndvi2017 = (frame.AVG_2017)

#ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi2013,ndvi2014,ndvi2015,ndvi2016))
ndvidata1 = np.vstack((ndvi2013,ndvi2014,ndvi2015,ndvi2016,ndvi2017))

#yeardata = np.empty([1,1])
yeardata = np.vstack((year1,year2,year3,year4))
yeardata1 = np.vstack((year1,year2,year3,year4,year5))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

print(yeardata.shape[0])
ndvidata = ndvidata.T 
ndvidata1 = ndvidata1.T 
print("ndvi shape is")
print(ndvidata.shape)
ndvidata = ndvidata[yeardata1.min(axis=1)>=0,:]
ndvidata1 = ndvidata1[yeardata1.min(axis=1)>=0,:]
yeardata = yeardata[yeardata1.min(axis=1)>=0,:]
print("yeardata shape is")
print(yeardata.shape[0])
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

year = np.array((yeardata))
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
ndvidata = ndvidata.tolist()
ndvidata1 = ndvidata1.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))
year1 = np.array((yeardata1))
ndvi1 = np.array((ndvidata1))

inputs = np.dstack((year,ndvi))
inputs1 = np.dstack((year1,ndvi1))

inputs = np.reshape(inputs,(32,4,2))
inputs1 = np.reshape(inputs1,(32,5,2))

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=4, X=inputs ,algorithm='baum-welch', verbose=False, emission_pseudocount=1, end_state=False)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
counter_mat = 0
counter_prob = 0
class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0

for j in range(temps,32):
    matrix =[]
    comparison = inputs1[j][4][0]
    
    for i in range(0,5):
        temph = inputs1[j][:][:]
        #print(temph.shape)
        temph[4][0] = i
        probability = model.log_probability(temph)
        matrix.append(probability)
    ind = matrix.index(max(matrix))
    if comparison == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            #print("come here")
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1

print("accuracy_prob of afghanistan is")
print(counter_prob)
print(counter_prob/32)
print("classwise accuracies are")
print("Class 0")
print(class0/32)
print("Class 1")
print(class1/32)
print("Class 2")
print(class2/32)
print("Class 3")
print(class3/32)
print("Class 4")
print(class4/32)

34
34
ndvi shape is
(34, 4)
yeardata shape is
32
accuracy_prob of afghanistan is
20
0.625
classwise accuracies are
Class 0
0.0
Class 1
0.1875
Class 2
0.4375
Class 3
0.0
Class 4
0.0


In [126]:
frame = pd.read_csv('jaspreet_mali.csv')
print("length is")
print(len(frame.Country))
year0 = (frame.jaspreet_2013)
year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)

yeardata = np.empty([1,1])

ndvi1 = (frame.ndvi_13_2)
ndvi2 = (frame.ndvi_14_2)
ndvi3 = (frame.ndvi_15_1)
ndvi4 = (frame.ndvi_15_2)
ndvi5 = (frame.ndvi_16_1)
ndvi6 = (frame.ndvi_16_2)
ndvi7 = (frame.ndvi_17_1)
ndvi8 = (frame.ndvi_17_2)
ndvi9 = (frame.ndvi_18_1)
yeardata = np.vstack((year0,year1,year2,year3,year4,year5,year6,year7))
yeardata1 = np.vstack((year0,year1,year2,year3,year4,year5,year6,year7,year8))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]
#print(yeardata1)

ndvidata = np.vstack((ndvi1,ndvi2,ndvi3,ndvi4,ndvi5,ndvi6,ndvi7,ndvi8))
ndvidata1 = np.vstack((ndvi1,ndvi2,ndvi3,ndvi4,ndvi5,ndvi6,ndvi7,ndvi8,ndvi9))

ndvidata = ndvidata.T 
ndvidata1 = ndvidata1.T 

print("ndvi shape is")
print(ndvidata.shape)
yeardata = yeardata[yeardata1.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print("yeardata1 shape is")
print(yeardata1.shape)
ndvidata = ndvidata[yeardata1.min(axis=1)>=0,:]
ndvidata1 = ndvidata1[yeardata1.min(axis=1)>=0,:]
year = np.array((yeardata))
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
ndvidata = ndvidata.tolist()
ndvidata1 = ndvidata1.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))
year1 = np.array((yeardata1))
ndvi1 = np.array((ndvidata1))

inputs = np.dstack((year,ndvi))
inputs1 = np.dstack((year1,ndvi1))

inputs = np.reshape(inputs,(49,8,2))
inputs1 = np.reshape(inputs1,(49,9,2))

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=5, X=inputs ,algorithm='baum-welch', verbose=False, emission_pseudocount=0.5, end_state=False)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
counter_mat = 0
counter_prob = 0



for j in range(temps,49):
    matrix =[]
    comparison = inputs1[j][8][0]
    
    for i in range(0,5):
        temph = inputs1[j][:][:]
        #print(temph.shape)
        temph[8][0] = i
        probability = model.log_probability(temph)
        matrix.append(probability)
    ind = matrix.index(max(matrix))
    if comparison == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            #print("come here")
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1

print("accuracy_prob is")
print(counter_prob)
print(counter_prob/49)

print("classwise accuracies are")
print("Class 0")
print(class0/49)
print("Class 1")
print(class1/49)
print("Class 2")
print(class2/49)
print("Class 3")
print(class3/49)
print("Class 4")
print(class4/49)

length is
49
ndvi shape is
(49, 8)
yeardata1 shape is
(49, 9)
accuracy_prob is
40
0.8163265306122449
classwise accuracies are
Class 0
7.877551020408164
Class 1
0.9183673469387755
Class 2
0.02040816326530612
Class 3
0.0
Class 4
0.0


In [10]:
#Experimenting with Multivariate Gaussian Distribution
#######OLDEST model, ignore
frame = pd.read_csv('jaspreet_afghanistan.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2013)
year2 = (frame.jaspreet_2014)
year3 = (frame.jaspreet_2015)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2017)

ndvi2012 = (frame.AVG_2012)
ndvi2013 = (frame.AVG_2013)
ndvi2014 = (frame.AVG_2014)
ndvi2015 = (frame.AVG_2015)
ndvi2016 = (frame.AVG_2016)
ndvi2017 = (frame.AVG_2017)

ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi2013,ndvi2014,ndvi2015,ndvi2016))

yeardata = np.empty([1,1])
yeardata = np.vstack((year1,year2,year3,year4))
yeardata = yeardata.T - 1

yeardata1 = np.vstack((year1,year2,year3,year4,year5))
yeardata1 = yeardata1.T - 1
ndvidata = ndvidata.T - 1

test = np.hstack((year1,year2,year3,year4))

print("yay jassu")
print(test.shape)


#print("shape of ndvi is")
#print(ndvidata.shape)
#print(yeardata)

testcase = (yeardata.min(axis=1)>=0)
#print((yeardata.min(axis=1)>=0))
dim = yeardata.shape[0]-1
for i in range(0, dim):
    if testcase[dim - i] == False:
        print(dim-i)
        ndvidata = np.delete(ndvidata,i,0)
        
yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print(ndvidata.shape)

print("new shape is")
print(yeardata.shape)
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
#print("new list is")
#print(yeardata)
#print("after turning to list")
#print(yeardata.shape)

ndvidata = ndvidata.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))

#print("year is")
#print(year)
#print("ndvi is")
#print(ndvi)
inputs = np.vstack((year,ndvi))
#print(year.shape)
#print(ndvi.shape)
inputs = np.reshape(inputs,(2,32,4))
print(inputs.shape)
#print("inputs shape is")
#print(np.reshape(year,(1,128)))
#print(inputs)

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=5, X=inputs ,algorithm='baum-welch', verbose=False, emission_pseudocount=1, end_state=True)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
print(yeardata1)
counter_mat = 0
counter_prob = 0
#print("here we go")
#print(model.d)
#print("input shape is")
#print(inputs.shape)
for j in range(temps,32):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix =[]
    for i in range(0,4):
        
        sequence = []
        temp = []
        
        
        temp = inputs[0][j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        print("temp is")
        print(temp)
        if len(temp) == 4:
            temp = np.append(temp,i)
            print("new temp is")
            print(temp)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[4] = i
            print("temp for else case is")
            print(temp)
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        #print("trans and ems matrices")
        #print(trans)
        #print("ems")
        #print(ems)
        ###from here commenting out
        #print("ems is")
        #print(ems)
        #ind1 = np.argmax(ems[4,:])
        temp = temp[:-1]
        print("final temp is")
        print(temp)
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 4:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    #if yeardata1[j][4] == ind1:
        
    #    counter_mat +=1
    if yeardata1[j][4] == ind:
        counter_prob +=1

#print(counter)
#print("accuracy_mat is")
#print(counter_mat/32)
print("accuracy_prob is")
print(counter_prob)
print(counter_prob/32)

34
yay jassu
(136,)
21
18
(32, 4)
new shape is
(32, 4)
(2, 32, 4)
[[3, 3, 2, 2, 2], [2, 2, 1, 2, 3], [1, 1, 1, 2, 1], [2, 2, 1, 1, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 2], [3, 2, 2, 2, 2], [0, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 2, 1, 1, 1], [0, 0, 1, 1, 1], [1, 1, 1, 2, 2], [2, 1, 1, 2, 2], [0, 1, 1, 1, 2], [1, 1, 1, 2, 2], [1, 1, 1, 2, 1], [2, 1, 1, 1, 1], [1, 1, 1, 2, 2], [2, 2, 2, 2, 2], [2, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [2, 2, 1, 1, 2], [1, 2, 1, 2, 1], [1, 2, 1, 1, 2], [1, 1, 1, 2, 2], [1, 2, 0, 1, 1], [2, 2, 1, 2, 2], [2, 1, 1, 1, 2]]
temp is
[3. 3. 2. 2.]
new temp is
[3. 3. 2. 2. 0.]
final temp is
[3. 3. 2. 2.]
temp is
[3. 3. 2. 2.]
new temp is
[3. 3. 2. 2. 1.]
final temp is
[3. 3. 2. 2.]
temp is
[3. 3. 2. 2.]
new temp is
[3. 3. 2. 2. 2.]
final temp is
[3. 3. 2. 2.]
temp is
[3. 3. 2. 2.]
new temp is
[3. 3. 2. 2. 3.]
final temp is
[3. 3. 2. 2.]
temp is
[2. 2. 1. 2.]
new temp is
[2. 2. 1. 2. 0.]
final temp is
[2. 2. 1

final temp is
[1. 1. 1. 2.]
temp is
[1. 1. 1. 2.]
new temp is
[1. 1. 1. 2. 2.]
final temp is
[1. 1. 1. 2.]
temp is
[1. 1. 1. 2.]
new temp is
[1. 1. 1. 2. 3.]
final temp is
[1. 1. 1. 2.]
temp is
[1. 2. 0. 1.]
new temp is
[1. 2. 0. 1. 0.]
final temp is
[1. 2. 0. 1.]
temp is
[1. 2. 0. 1.]
new temp is
[1. 2. 0. 1. 1.]
final temp is
[1. 2. 0. 1.]
temp is
[1. 2. 0. 1.]
new temp is
[1. 2. 0. 1. 2.]
final temp is
[1. 2. 0. 1.]
temp is
[1. 2. 0. 1.]
new temp is
[1. 2. 0. 1. 3.]
final temp is
[1. 2. 0. 1.]
temp is
[2. 2. 1. 2.]
new temp is
[2. 2. 1. 2. 0.]
final temp is
[2. 2. 1. 2.]
temp is
[2. 2. 1. 2.]
new temp is
[2. 2. 1. 2. 1.]
final temp is
[2. 2. 1. 2.]
temp is
[2. 2. 1. 2.]
new temp is
[2. 2. 1. 2. 2.]
final temp is
[2. 2. 1. 2.]
temp is
[2. 2. 1. 2.]
new temp is
[2. 2. 1. 2. 3.]
final temp is
[2. 2. 1. 2.]
temp is
[2. 1. 1. 1.]
new temp is
[2. 1. 1. 1. 0.]
final temp is
[2. 1. 1. 1.]
temp is
[2. 1. 1. 1.]
new temp is
[2. 1. 1. 1. 1.]
final temp is
[2. 1. 1. 1.]
temp is
[2. 1. 1. 1.]
ne