In [1]:
import numpy as np
#from sklearn
from pomegranate import *
import pandas as pd
from collections import Counter

In [2]:
model = HiddenMarkovModel()

In [3]:
#Experimenting with Multivariate Gaussian Distribution

frame = pd.read_csv('jaspreet_afghanistan.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2013)
year2 = (frame.jaspreet_2014)
year3 = (frame.jaspreet_2015)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2017)

ndvi2012 = (frame.AVG_2012)
ndvi2013 = (frame.AVG_2013)
ndvi2014 = (frame.AVG_2014)
ndvi2015 = (frame.AVG_2015)
ndvi2016 = (frame.AVG_2016)
ndvi2017 = (frame.AVG_2017)

ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi2013,ndvi2014,ndvi2015,ndvi2016))
yeardata = np.empty([1,1])
yeardata = np.vstack((year1,year2,year3,year4))
yeardata = yeardata.T - 1

yeardata1 = np.vstack((year1,year2,year3,year4,year5))
yeardata1 = yeardata1.T - 1
ndvidata = ndvidata.T - 1

test = np.hstack((year1,year2,year3,year4))

print("yay jassu")
print(test.shape)


#print("shape of ndvi is")
#print(ndvidata.shape)
#print(yeardata)

testcase = (yeardata.min(axis=1)>=0)
#print((yeardata.min(axis=1)>=0))
dim = yeardata.shape[0]-1
for i in range(0, dim):
    if testcase[dim - i] == False:
        print(dim-i)
        ndvidata = np.delete(ndvidata,i,0)
        
yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print(ndvidata.shape)

print("new shape is")
print(yeardata.shape)
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
#print("new list is")
#print(yeardata)
#print("after turning to list")
#print(yeardata.shape)

ndvidata = ndvidata.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))

#print("year is")
#print(year)
#print("ndvi is")
#print(ndvi)
inputs = np.vstack((year,ndvi))
#print(year.shape)
#print(ndvi.shape)
inputs = np.reshape(inputs,(2,32,4))
print(inputs.shape)
#print("inputs shape is")
#print(np.reshape(year,(1,128)))
#print(inputs)

model = HiddenMarkovModel.from_samples(MultivariateGaussianDistribution, n_components=3, X=inputs ,algorithm='viterbi', verbose=False, emission_pseudocount=1, end_state=True)
count = 0
output_diagnol = []
dictionary = {}
temps = 0
print(yeardata1)
counter_mat = 0
counter_prob = 0
#print("here we go")
#print(model.d)
#print("input shape is")
#print(inputs.shape)
for j in range(temps,32):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix =[]
    for i in range(0,4):
        
        sequence = []
        temp = []
        
        
        temp = inputs[0][j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        #print("temp is")
        #print(temp)
        if len(temp) == 4:
            temp = np.append(temp,i)
            print("new temp is")
            print(temp)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[4] = i
            #print("temp for else case is")
            #print(temp)
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        #print("trans and ems matrices")
        #print(trans)
        #print("ems")
        #print(ems)
        ###from here commenting out
        #print("ems is")
        #print(ems)
        #ind1 = np.argmax(ems[4,:])
        temp = temp[:-1]
        #print("final temp is")
        #print(temp)
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 4:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    #if yeardata1[j][4] == ind1:
        
    #    counter_mat +=1
    if yeardata1[j][4] == ind:
        counter_prob +=1

#print(counter)
#print("accuracy_mat is")
#print(counter_mat/32)
print("accuracy_prob is")
print(counter_prob)
print(counter_prob/32)

34
yay jassu
(136,)
21
18
(32, 4)
new shape is
(32, 4)
(2, 32, 4)
[[3, 3, 2, 2, 2], [2, 2, 1, 2, 3], [1, 1, 1, 2, 1], [2, 2, 1, 1, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 2], [3, 2, 2, 2, 2], [0, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 2, 1, 1, 1], [0, 0, 1, 1, 1], [1, 1, 1, 2, 2], [2, 1, 1, 2, 2], [0, 1, 1, 1, 2], [1, 1, 1, 2, 2], [1, 1, 1, 2, 1], [2, 1, 1, 1, 1], [1, 1, 1, 2, 2], [2, 2, 2, 2, 2], [2, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [2, 2, 1, 1, 2], [1, 2, 1, 2, 1], [1, 2, 1, 1, 2], [1, 1, 1, 2, 2], [1, 2, 0, 1, 1], [2, 2, 1, 2, 2], [2, 1, 1, 1, 2]]
new temp is
[3. 3. 2. 2. 0.]
new temp is
[3. 3. 2. 2. 1.]
new temp is
[3. 3. 2. 2. 2.]
new temp is
[3. 3. 2. 2. 3.]
new temp is
[2. 2. 1. 2. 0.]
new temp is
[2. 2. 1. 2. 1.]
new temp is
[2. 2. 1. 2. 2.]
new temp is
[2. 2. 1. 2. 3.]
new temp is
[1. 1. 1. 2. 0.]
new temp is
[1. 1. 1. 2. 1.]
new temp is
[1. 1. 1. 2. 2.]
new temp is
[1. 1. 1. 2. 3.]
new temp is
[2. 2. 1. 1. 0.]
new temp is


In [6]:
'''
yeardata, no of compos = 3
accuracy_mat is
0.6785714285714286
accuracy_prob is
0.5714285714285714

'''


frame = pd.read_csv('jaspreet_somalia.csv')

print(len(frame.Country))
#year0 = (frame.jaspreet_2010)
#year1 = (frame.jaspreet_2011)
#year2 = (frame.jaspreet_2011_2)
year3 = (frame.jaspreet_2012)
year4 = (frame.jaspreet_2012_2)
year5 = (frame.jaspreet_2013)
year6 = (frame.jaspreet_2013_2)
year7 = (frame.jaspreet_2014)
year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])
yeardata1 = np.vstack((year3,year4,year5,year6,year7,year8,year9,year10,year11,year12,year13,year14,year15))
yeardata = np.vstack((year3,year4,year5,year6,year7,year8,year9,year10,year11,year12,year13,year14))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

#print(yeardata1)

yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print(yeardata1.shape[0])
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
#print(yeardata)
#year = np.array((yeardata))

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=3, X=yeardata ,algorithm='baum-welch', emission_pseudocount=0.25, end_state=True)

count = 0
output_diagnol = []
output = {}
temp = 0
counter_mat = 0
counter_prob = 0
#print("here we go")
#print(model.d)

''''''

class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0
dictionary = []

''''''
for j in range(temp,56):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix =[]
    for i in range(0,4):
        
        sequence = []
        temp = []
        
        
        temp = yeardata[j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        if len(temp) == 11:
            temp.append(i)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[11] = i
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        #print("trans and ems matrices")
        #print(trans)
        print("ems")
        print(ems)
        ind1 = np.argmax(ems[11,:])
        temp = temp.pop()
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 4:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    if yeardata1[j][11] == ind1:
        
        counter_mat +=1
        #print("ind1 is")
        #print(ind1)
        if ind1==0:
            class0 += 1
        elif ind1==1:
            class1 += 1
        elif ind1==2:
            #print("come here")
            class2 += 1
        elif ind1==3:
            class3 += 1
        elif ind1==4:
            class4 += 1
            
    else:
        dictionary.append((yeardata1[j][11],ind1))
    if yeardata1[j][11] == ind:
        counter_prob +=1

        
        
#print(counter)
print("accuracy_mat is")
print(counter_mat/56)
print("classwise accuracies are")
print("Class 0")
print(class0/56)
print("Class 1")
print(class1/56)
print("Class 2")
print(class2/56)
print("Class 3")
print(class3/56)
print("Class 4")
print(class4/56)

print("missclassifications are")
print("format is actual, misclassified")
print(Counter(dictionary))
#print("accuracy_prob is")
#print(counter_prob/56)

73
56
ems
[[-3.57502926e+00 -4.43442297e-02 -4.17593700e+00]
 [-2.40594179e+00 -9.48163771e-02 -8.18235010e+00]
 [-1.73317898e+00 -1.94845671e-01 -8.05779471e+00]
 [-1.21868030e+00 -3.50929575e-01 -7.96725958e+00]
 [-7.78082727e-01 -6.15317929e-01 -8.31335807e+00]
 [-3.78606743e-01 -1.15460903e+00 -1.23354135e+01]
 [-4.85116915e-03 -5.33486791e+00 -1.08777035e+01]
 [-1.73710527e-03 -7.72913001e+00 -6.64864956e+00]
 [-3.59641428e-03 -6.39938948e+00 -6.25159219e+00]
 [-4.00883075e-03 -5.74807949e+00 -7.11612489e+00]
 [-2.76209111e-03 -5.93316835e+00 -9.13145782e+00]
 [-8.91952198e-03 -1.49289070e+01 -4.72400636e+00]]
ems
[[-3.57502849e+00 -4.43442511e-02 -4.17593708e+00]
 [-2.40594102e+00 -9.48164541e-02 -8.18235027e+00]
 [-1.73317820e+00 -1.94845839e-01 -8.05779504e+00]
 [-1.21867952e+00 -3.50929904e-01 -7.96726025e+00]
 [-7.78081941e-01 -6.15318596e-01 -8.31335981e+00]
 [-3.78605955e-01 -1.15461074e+00 -1.23356440e+01]
 [-4.85032645e-03 -5.33503407e+00 -1.08797020e+01]
 [-1.73332535e-0

ems
[[-8.92591574e+00 -8.14604459e+00 -4.22868798e-04]
 [-1.25101529e+01 -2.84515994e+00 -5.98865940e-02]
 [-5.94730465e+00 -1.04822392e-02 -4.85175915e+00]
 [-2.71521734e+00 -6.85659976e-02 -9.46393980e+00]
 [-1.87197125e+00 -1.67302109e-01 -8.35231327e+00]
 [-1.29424254e+00 -3.20776200e-01 -8.08226395e+00]
 [-8.21871913e-01 -5.79541997e-01 -8.34675909e+00]
 [-4.04050596e-01 -1.10150620e+00 -1.08415968e+01]
 [-1.95086356e-02 -3.97204661e+00 -7.63192347e+00]
 [-1.57886100e-02 -4.20810530e+00 -7.14335238e+00]
 [-9.68213835e-03 -4.67245920e+00 -8.15893227e+00]
 [-2.35218614e-02 -9.24337665e+00 -3.76573335e+00]]
ems
[[-8.92585539e+00 -8.14563679e+00 -4.22995112e-04]
 [-1.25021883e+01 -2.84481368e+00 -5.99079976e-02]
 [-5.93926680e+00 -1.04989424e-02 -4.85234254e+00]
 [-2.70712536e+00 -6.91419921e-02 -9.46543710e+00]
 [-1.86383951e+00 -1.68786986e-01 -8.35543417e+00]
 [-1.28608168e+00 -3.23873780e-01 -8.08877993e+00]
 [-8.13689734e-01 -5.86003409e-01 -8.36369877e+00]
 [-3.95847748e-01 -1.1

In [11]:
#yeardata, baum-welch, 2 compos, yeardata
#accuracy_mat is
#0.20270270270270271
#accuracy_prob is
#0.7162162162162162

frame = pd.read_csv('jaspreet_southsudan.csv')

print(len(frame.country))
#print(len(frame.country))

year7 = (frame.jaspreet_2014)
#year8 = (frame.jaspreet_2014_2)
year9 = (frame.jaspreet_2015)
year10 = (frame.jaspreet_2015_2)
year11 = (frame.jaspreet_2016)
year12 = (frame.jaspreet_2016_2)
year13 = (frame.jaspreet_2017)
year14 = (frame.jaspreet_2017_2)
year15 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])

#print(yeardata)
yeardata1 = np.vstack((year7,year9,year10,year11,year12,year13,year14,year15))
yeardata = np.vstack((year7,year9,year10,year11,year12,year13,year14))

yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

#print(yeardata1)

yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print(yeardata1.shape[0])
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
print(len(yeardata))
year = np.array((yeardata))

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=3, X=yeardata ,algorithm='baum-welch', emission_pseudocount=0.1, end_state=True)

count = 0
output_diagnol = []
output = {}
temp = 0
counter_mat = 0
counter_prob = 0

''''''

class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0
dictionary = []

''''''
#print("here we go")
#print(model.d)
for j in range(temp,74):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix =[]
    for i in range(0,5):
        
        sequence = []
        temp = []
        
        
        temp = yeardata[j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        if len(temp) == 7:
            temp.append(i)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[7] = i
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        print("trans matrix is")
        print(trans)
        #print("ems")
        #print(ems)
        ind1 = np.argmax(ems[7,:])
        temp = temp.pop()
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 3:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    if yeardata1[j][7] == ind1:
        
        counter_mat +=1
    if yeardata1[j][7] == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            #print("come here")
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1
    else:
        dictionary.append((yeardata1[j][7],ind))
        

print(counter)
#print("accuracy_mat is")
#print(counter_mat/74)
print("accuracy_prob is")
print(counter_prob/74)

print("classwise accuracies are")
print("Class 0")
print(class0/74)
print("Class 1")
print(class1/74)
print("Class 2")
print(class2/74)
print("Class 3")
print(class3/74)
print("Class 4")
print(class4/74)

print("missclassifications are")
print("format is actual, misclassified")
print(Counter(dictionary))

78
74
74
trans matrix is
[[7.26627125e-01 1.96904196e-36 8.44600331e-01 0.00000000e+00
  1.09425099e-01]
 [1.18949328e-01 1.69873690e-01 7.28168768e-20 0.00000000e+00
  2.62833387e-01]
 [1.65016964e-15 3.81782714e-01 4.75816681e+00 0.00000000e+00
  6.27741514e-01]
 [8.35076102e-01 4.81788238e-40 1.64923898e-01 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]
trans matrix is
[[6.48422760e-01 4.03961364e-37 8.56901847e-01 0.00000000e+00
  1.02068929e-02]
 [2.44561381e-02 3.43971414e-02 7.76396840e-20 0.00000000e+00
  4.66546423e-02]
 [3.10446860e-16 7.11107804e-02 5.36471133e+00 0.00000000e+00
  9.43138465e-01]
 [8.42652602e-01 4.63891070e-40 1.57347398e-01 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]
trans matrix is
[[6.40463851e-01 5.15758169e-37 8.49392733e-01 0.00000000e+00
  6.16386967e-06]
 [5.92166308e-03 4.41200606e-02 7.79365368e-20 0.00000000e+00

  0.00000000e+00]]
trans matrix is
[[2.24454537e-03 3.94516252e-38 6.05528953e-01 0.00000000e+00
  3.01592464e-02]
 [3.02077461e-02 3.30706638e-01 2.79608037e-20 0.00000000e+00
  4.10845096e-01]
 [4.09224190e-16 4.41052842e-01 5.59025928e+00 0.00000000e+00
  5.58995658e-01]
 [6.05480453e-01 1.53702930e-40 3.94519547e-01 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]
trans matrix is
[[2.15946215e-03 7.39101361e-39 6.05928986e-01 0.00000000e+00
  3.07251801e-03]
 [3.13098270e-03 6.21408634e-02 3.25124233e-20 0.00000000e+00
  7.96507341e-02]
 [4.27587859e-17 8.27817168e-02 6.24385799e+00 0.00000000e+00
  9.17276748e-01]
 [6.05870521e-01 3.01174163e-41 3.94129479e-01 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]
trans matrix is
[[2.13316640e-03 6.04072603e-38 6.05266876e-01 0.00000000e+00
  1.30287724e-06]
 [4.22875397e-05 5.54200441e-01 2.45438534e-20 0.00

NameError: name 'counter' is not defined

In [293]:

'''
yeardata 1, baum-welch, 5 compo

accuracy_mat is
0.0
accuracy_prob is
0.875

yeardata, compos = 2, baum-welch
accuracy_mat is
0.122
accuracy_prob is
0.857
'''
frame = pd.read_csv('jaspreet_mali.csv')

print(len(frame.Country))
year0 = (frame.jaspreet_2013)
year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)

yeardata = np.empty([1,1])

#print(yeardata)
yeardata = np.vstack((year0,year1,year2,year3,year4,year5,year6,year7))
yeardata1 = np.vstack((year0,year1,year2,year3,year4,year5,year6,year7,year8))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1

yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]
print(yeardata1)

yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
print(len(yeardata))
year = np.array((yeardata))

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=2, X=yeardata ,algorithm='baum-welch', emission_pseudocount=1, end_state=True)

count = 0
output_diagnol = []
output = {}
temp = 0
counter_mat = 0
counter_prob = 0
#print("here we go")
#print(model.d)

''''''

class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0
dictionary = []

''''''

for j in range(temp,49):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix = []
    for i in range(0,3):
        
        sequence = []
        temp = []
        
        
        temp = yeardata[j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        if len(temp) == 7:
            temp.append(i)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[7] = i
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        #print("trans and ems matrices")
        #print(trans)
        #print("ems")
        #print(ems)
        ind1 = np.argmax(ems[7,:])
        temp = temp.pop()
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 3:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    if yeardata1[j][7] == ind1:
        
        counter_mat +=1
    if yeardata1[j][7] == ind:
        counter_prob +=1
        if ind==0:
            class0 += 1
        elif ind==1:
            class1 += 1
        elif ind==2:
            #print("come here")
            class2 += 1
        elif ind==3:
            class3 += 1
        elif ind==4:
            class4 += 1
    else:
        dictionary.append((yeardata1[j][7],ind))
        

#print(counter)
#print("accuracy_mat is")
#print(counter_mat/49)
print("accuracy_prob is")
print(counter_prob/49)

print("classwise accuracies are")
print("Class 0")
print(class0/49)
print("Class 1")
print(class1/49)
print("Class 2")
print(class2/49)
print("Class 3")
print(class3/49)
print("Class 4")
print(class4/49)

print("missclassifications are")
print("format is actual, misclassified")
print(Counter(dictionary))

49
[[1 2 1 0 0 0 1 0 0]
 [2 2 2 0 0 1 1 0 1]
 [1 2 1 0 0 1 1 0 0]
 [2 2 1 0 1 1 2 1 2]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [2 2 1 1 1 0 0 0 0]
 [2 2 0 1 1 0 0 0 1]
 [2 1 0 0 1 0 0 1 1]
 [2 2 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 2]
 [1 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 2 1 0 0 0 0 0 0]
 [1 2 1 1 0 0 0 1 1]
 [2 2 2 1 0 0 1 1 1]
 [2 2 1 1 

In [294]:
#Viterbi and yeardata 
#2 components - 60.4%

'''
#EMISSION MATRIX, BUAM-WELCH, yeardata 

5 compo
accuracy_mat is
0.1875
accuracy_prob is
0.1875

4 compo
accuracy_mat is
0.1875
accuracy_prob is
0.1875


#3 compo 
accuracy_mat is
0.20833333333333334
accuracy_prob is
0.1875

2 compo
accuracy_mat is
0.3958333333333333
accuracy_prob is
0.20833333333333334

#EMISSION MATRIX, BUAM-WELCH, yeardata1 
5 compo
accuracy_mat is
0.1875
accuracy_prob is
0.1875

4 compo
accuracy_mat is
0.1875
accuracy_prob is
0.1875


#3 compo 
accuracy_mat is
0.2916666666666667
accuracy_prob is
0.6666666666666666

2 compo
accuracy_mat is
0.3958333333333333
accuracy_prob is
0.20833333333333334
'''
'''viterbi and yeardata
5 compos
accuracy_mat is
0.1875
accuracy_prob is
0.25

4 compos
accuracy_mat is
0.10416666666666667
accuracy_prob is
0.25

3 compos
accuracy_mat is
0.1875
accuracy_prob is
0.20833333333333334

2 compos 
accuracy_mat is
0.6041666666666666
accuracy_prob is
0.20833333333333334
'''

'''viterbi and yeardata1
5 compos
accuracy_mat is
0.08333333333333333
accuracy_prob is
0.6458333333333334

4 compos
accuracy_mat is
0.08333333333333333
accuracy_prob is
0.6666666666666666

3 compos
accuracy_mat is
0.1875
accuracy_prob is
0.6041666666666666

2 compos 
accuracy_mat is
0.20833333333333334
accuracy_prob is
0.6041666666666666
'''

''''''

class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0
dictionary = []

''''''

frame = pd.read_csv('jaspreet_niger.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2014)
year2 = (frame.jaspreet_2015)
year3 = (frame.jaspreet_2015_2)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2016_2)
year6 = (frame.jaspreet_2017)
year7 = (frame.jaspreet_2017_2)
year8 = (frame.jaspreet_2018)



yeardata = np.empty([1,1])


yeardata = np.vstack((year1,year2,year3,year4,year5,year6,year7))

yeardata1 = np.vstack((year1,year2,year3,year4,year5,year6,year7,year8))
yeardata = yeardata.T - 1
yeardata1 = yeardata1.T - 1
#print(yeardata)

yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

#print("new shape is")
#print(yeardata.shape)

yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
print(len(yeardata))
#print("new list is")
#print(yeardata1)


#ndvidata = ndvidata.tolist()

year = np.array((yeardata))
#ndvi = np.array((ndvidata))

#data = np.vstack((year,ndvi))

#print(data.shape)




#print(yeardata)

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=2, X=yeardata ,algorithm='viterbi', emission_pseudocount=0.1, end_state=True)

#print(model.emissionstates)
#output = model.predict_proba(yeardata[1])
#print(output)

count = 0
output_diagnol = []
output = {}
temp = 0
counter_mat = 0
counter_prob = 0
#print("here we go")
#print(model.d)
for j in range(temp,48):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix = []
    for i in range(0,3):
        
        sequence = []
        temp = []
        
        
        temp = yeardata[j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        if len(temp) == 7:
            temp.append(i)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[7] = i
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        #print("trans and ems matrices")
        #print(trans)
        #print("ems")
        #print(ems)
        ind1 = np.argmax(ems[7,:])
        temp = temp.pop()
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 3:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    if yeardata1[j][7] == ind1:
        
        counter_mat +=1
        
        if ind1==0:
            class0 += 1
        elif ind1==1:
            class1 += 1
        elif ind1==2:
            #print("come here")
            class2 += 1
        elif ind1==3:
            class3 += 1
        elif ind1==4:
            class4 += 1
            
    else:
        dictionary.append((yeardata1[j][7],ind1))
    if yeardata1[j][7] == ind:
        counter_prob +=1

print(counter)
print("accuracy_mat is")
print(counter_mat/48)
#print("accuracy_prob is")
#print(counter_prob/48)

print("classwise accuracies are")
print("Class 0")
print(class0/48)
print("Class 1")
print(class1/48)
print("Class 2")
print(class2/48)
print("Class 3")
print(class3/48)
print("Class 4")
print(class4/48)

print("missclassifications are")
print("format is actual, misclassified")
print(Counter(dictionary))

        

61
48
14
accuracy_mat is
0.6041666666666666
classwise accuracies are
Class 0
0.0
Class 1
0.6041666666666666
Class 2
0.0
Class 3
0.0
Class 4
0.0
missclassifications are
format is actual, misclassified
Counter({(0, 1): 10, (2, 1): 9})


In [296]:
frame = pd.read_csv('jaspreet_afghanistan.csv')

print(len(frame.Country))

year1 = (frame.jaspreet_2013)
year2 = (frame.jaspreet_2014)
year3 = (frame.jaspreet_2015)
year4 = (frame.jaspreet_2016)
year5 = (frame.jaspreet_2017)

ndvi2012 = (frame.AVG_2012)
ndvi2013 = (frame.AVG_2013)
ndvi2014 = (frame.AVG_2014)
ndvi2015 = (frame.AVG_2015)
ndvi2016 = (frame.AVG_2016)
ndvi2017 = (frame.AVG_2017)

ndvidata = np.empty([1,1])
ndvidata = np.vstack((ndvi2013,ndvi2014,ndvi2015,ndvi2016))
yeardata = np.empty([1,1])
yeardata = np.vstack((year1,year2,year3,year4))
yeardata = yeardata.T - 1

yeardata1 = np.vstack((year1,year2,year3,year4,year5))
yeardata1 = yeardata1.T - 1
ndvidata = ndvidata.T - 1


#print("shape of ndvi is")
#print(ndvidata.shape)
#print(yeardata)

testcase = (yeardata.min(axis=1)>=0)
#print((yeardata.min(axis=1)>=0))
dim = yeardata.shape[0]-1
for i in range(0, dim):
    if testcase[dim - i] == False:
        print(dim-i)
        ndvidata = np.delete(ndvidata,i,0)
        
yeardata = yeardata[yeardata.min(axis=1)>=0,:]
yeardata1 = yeardata1[yeardata1.min(axis=1)>=0,:]

print(ndvidata.shape)

print("new shape is")
print(yeardata.shape)
yeardata = yeardata.tolist()
yeardata1 = yeardata1.tolist()
#print("new list is")
#print(yeardata)


ndvidata = ndvidata.tolist()

year = np.array((yeardata))
ndvi = np.array((ndvidata))

model = HiddenMarkovModel.from_samples(DiscreteDistribution, n_components=3, X=yeardata ,algorithm='viterbi', verbose=False, emission_pseudocount=0.1, end_state=True)
count = 0
output_diagnol = []
output = {}
temp = 0
print(yeardata1)
counter_mat = 0
counter_prob = 0

''''''

class0 = 0
class1 = 0
class2 = 0
class3 = 0
class4 = 0
dictionary = []

''''''
#print("here we go")
#print(model.d)
for j in range(temp,32):
    #print("next j value")
    #print(j)
    #print("yeardata1 is")
    #print(yeardata1[j])
    matrix =[]
    for i in range(0,4):
        
        sequence = []
        temp = []
        
        
        temp = yeardata[j]
        #print(type(temp))
        #print(yeardata[j])
        #print(i)
        if len(temp) == 4:
            temp.append(i)
            sequence = temp
            
        else:
            #print(len(temp))
            #print("temp is")
            #print(temp)
            temp[4] = i
            sequence = temp
        #print("length of sequence is")
        #print(sequence)
        #del sequence[:]
        
        #print("new length is")
        #print(len(sequence))
        probability = model.log_probability(sequence)
        #print("probability is")
        #print(probability)
        matrix.append(probability)
        trans, ems = model.forward_backward(sequence)
        #print("trans and ems matrices")
        #print(trans)
        #print("ems")
        #print(ems.shape)
        ind1 = np.argmax(ems[4,:])
        temp = temp.pop()
    count = 0
    for k in range(0, len(matrix)):
        
        if probability == matrix[k]:
            count +=1
            
    if count == 4:
        pass
        #print("All same")
    else :
        pass
        #print("Different values")
        
    #print("matrix is")
    #print(matrix)
    
    ind = np.argmax(matrix)
    #print("index is")
    #print(ind)
    #print("index1 is")
    #print(ind1)
    #print("required is")
    #print(yeardata1[j][7])
    
    if yeardata1[j][4] == ind1:
        
        counter_mat +=1
        if ind1==0:
            class0 += 1
        elif ind1==1:
            class1 += 1
        elif ind1==2:
            #print("come here")
            class2 += 1
        elif ind1==3:
            class3 += 1
        elif ind1==4:
            class4 += 1
            
    else:
        dictionary.append((yeardata1[j][4],ind1))
    if yeardata1[j][4] == ind:
        counter_prob +=1
        

print(counter)
print("accuracy_mat is")
print(counter_mat/32)
print("accuracy_prob is")
print(counter_prob/32)

print("classwise accuracies are")
print("Class 0")
print(class0/32)
print("Class 1")
print(class1/32)
print("Class 2")
print(class2/32)
print("Class 3")
print(class3/32)
print("Class 4")
print(class4/32)

print("missclassifications are")
print("format is actual, misclassified")
print(Counter(dictionary))


    
    



34
21
18
(32, 4)
new shape is
(32, 4)
[[3, 3, 2, 2, 2], [2, 2, 1, 2, 3], [1, 1, 1, 2, 1], [2, 2, 1, 1, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 1], [2, 2, 1, 2, 2], [1, 1, 1, 2, 2], [3, 2, 2, 2, 2], [0, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 2, 1, 1, 1], [0, 0, 1, 1, 1], [1, 1, 1, 2, 2], [2, 1, 1, 2, 2], [0, 1, 1, 1, 2], [1, 1, 1, 2, 2], [1, 1, 1, 2, 1], [2, 1, 1, 1, 1], [1, 1, 1, 2, 2], [2, 2, 2, 2, 2], [2, 1, 1, 2, 2], [1, 1, 1, 2, 1], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [2, 2, 1, 1, 2], [1, 2, 1, 2, 1], [1, 2, 1, 1, 2], [1, 1, 1, 2, 2], [1, 2, 0, 1, 1], [2, 2, 1, 2, 2], [2, 1, 1, 1, 2]]
14
accuracy_mat is
0.59375
accuracy_prob is
0.59375
classwise accuracies are
Class 0
0.0
Class 1
0.0
Class 2
0.59375
Class 3
0.0
Class 4
0.0
missclassifications are
format is actual, misclassified
Counter({(1, 2): 12, (3, 2): 1})


In [ ]:
#of the type actual : predicted
'''
temp = 1
for i in range(temp,32):
    cool = model.predict_proba(yeardata[i])
    #print("cool shape")
    #print(cool.shape)
    
    if(np.argmax(cool[4,:],axis =0) == yeardata[i][4]):
        output_diagnol.append(yeardata[i][4])
        
        count+=1
    else:
        key = yeardata[i][4]
        output[key] = (np.argmax(cool[4,:],axis =0))                       
        
        
print("accuracy for Afghanistan is") 
print(count/(32-temp))
print(output)
print(output_diagnol)
'''
'''
#print(model.node_count())
print("length is")
print(len(yeardata))
count = 0
output_diagnol = []
output = {}
#of the type actual : predicted
temp = 1
for i in range(temp,len(yeardata)):
    #print("yeardata is")
    #print(yeardata[i])
    cool = model.predict_proba(yeardata[i])
    #print("cool is")
    #print(cool)
    cool1 = model.predict(yeardata[i], algorithm='map')
    #print("cool1 is")
    #print(cool1)
    cool2 = model.viterbi(yeardata[i])
    #print("cool2 is")
    #print(cool2)
    #print("shape of cool is")
    #print(cool.shape)
    if(cool1[4] == yeardata[i][4]):
        output_diagnol.append(yeardata[i][4])
        print("Theres a match!")
        #print("yeardata is")
        #print(yeardata[i,4])
        #key = yeardata[i,4]
        #output[key] = np.argmax(cool[4,:],axis =0)
        count+=1
    else:
        #print("else part here")
        #print(i)
        key = yeardata[i][4]
        #print("key is")
        #print(key)
        #print("value is")
        #print(np.argmax(cool[4,:],axis =0))
        output[key] = (cool1[4])                       
        
print("correct count is")
print(count)
print("accuracy for Afghanistan is") 
print(count/(len(frame.Country)-temp))
print(output)
print(output_diagnol)
'''
#print("model is")
#print(model)

#output = model.viterbi(yeardata[1])

#print(output)